create TABLE NEWS ( ID IDENTITY PRIMARY KEY  , CONTENT VARCHAR(250) , WRITTEN_BY INT , DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL );

create TABLE SESSION ( TOKEN VARCHAR ( 130 ) NOT NULL , IP_ADDRESS VARCHAR ( 100 ) NOT NULL , EXPIRE_DATE DATETIME NOT NULL );
create UNIQUE INDEX unique_TOKEN ON SESSION ( TOKEN );

create TABLE TICKET ( TICKET_NUMBER IDENTITY PRIMARY KEY, STATUS VARCHAR ( 10 ) DEFAULT 'New' , CATEGORY VARCHAR ( 50 ) DEFAULT 'Other' , SUBJECT VARCHAR ( 50 ) , SENDER_NAME VARCHAR ( 50 ) , SENDER_EMAIL VARCHAR ( 100 ) NOT NULL , MESSAGE VARCHAR(250) , DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL , REPLY_BY INT , REPLY_MESSAGE VARCHAR(250) , REPLY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL );
create TABLE USER ( USERNAME VARCHAR ( 25 ) PRIMARY KEY NOT NULL , PASSWORD BINARY ( 255 ) NOT NULL , SALT BINARY ( 255 ) NOT NULL );